#!/usr/bin/env python3
import re
import sys
import urllib.request
import xml.etree.ElementTree as ElementTree
from pathlib import Path

UNICODE = "17.0.0"
CLDR = "release-48-2"
TEST = f"https://www.unicode.org/Public/{UNICODE}/emoji/emoji-test.txt"
ANNOTATIONS = f"https://raw.githubusercontent.com/unicode-org/cldr/{CLDR}/common/{{}}/en.xml"
OUT = (
    Path(__file__).resolve().parent.parent
    / "Packages/ClipboardKit/Sources/ClipboardKit/Resources/emoji.tsv"
)
MEDIUM = "\U0001f3fd"
VARIATION = "️"
LINE = re.compile(r"^([0-9A-F ]+?)\s*; fully-qualified\s*# \S+ E[\d.]+ (.+)$")


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def keywords():
    found = {}
    for folder in ("annotations", "annotationsDerived"):
        root = ElementTree.fromstring(fetch(ANNOTATIONS.format(folder)))
        for annotation in root.iter("annotation"):
            if annotation.get("type") != "tts":
                words = [word.strip() for word in annotation.text.split("|")]
                found.setdefault(annotation.get("cp").replace(VARIATION, ""), words)
    return found


def toned(emoji):
    rest = emoji[1:]
    if rest.startswith(VARIATION):
        rest = rest[1:]
    return emoji[0] + MEDIUM + rest


def main():
    words = keywords()
    groups = []
    names = {}
    for line in fetch(TEST).splitlines():
        if line.startswith("# group: "):
            groups.append((line[len("# group: ") :], []))
            continue
        match = LINE.match(line)
        if not match or groups[-1][0] == "Component":
            continue
        emoji = "".join(chr(int(point, 16)) for point in match.group(1).split())
        name = match.group(2)
        names[name] = emoji
        if "skin tone" not in name:
            groups[-1][1].append((emoji, name))
    rows = [
        f"# Generated by scripts/emoji-data.py from Unicode {UNICODE} emoji-test.txt "
        f"and CLDR {CLDR} annotations.",
        "# © Unicode, Inc. Used under the Unicode License v3: https://www.unicode.org/license.txt",
    ]
    for group, emojis in groups:
        if not emojis:
            continue
        rows.append(f"@{group}")
        for emoji, name in emojis:
            extra = [
                word
                for word in words.get(emoji.replace(VARIATION, ""), [])
                if word.lower() not in name.lower().split() + [name.lower()]
            ]
            tone = "1" if names.get(f"{name}: medium skin tone") == toned(emoji) else ""
            rows.append("\t".join([emoji, name, "|".join(extra), tone]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(rows) + "\n", encoding="utf-8")
    sys.stdout.write(f"Wrote {len(rows)} lines to {OUT}\n")


main()
