name: Test Packages

on:
  workflow_call:

permissions:
  contents: read

jobs:
  list:
    name: List Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list.outputs.packages }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: list
        working-directory: Packages
        run: echo "packages=$(printf '%s\n' */ | jq -Rnc '[inputs | rtrimstr("/")]')" >> "$GITHUB_OUTPUT"

  test:
    name: ${{ matrix.package }}
    needs: list
    runs-on: xcode-27
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.list.outputs.packages) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run package tests
        env:
          PACKAGE: ${{ matrix.package }}
        run: swift test --package-path "Packages/$PACKAGE"
